/*
 * FaceRecognitionDotNet Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using FaceRecognitionDotNet.Client.Client;
using FaceRecognitionDotNet.Client.Api;
// uncomment below to import models
//using FaceRecognitionDotNet.Client.Model;

namespace FaceRecognitionDotNet.Client.Test.Api
{
    /// <summary>
    ///  Class for testing FaceRegistrationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class FaceRegistrationApiTests : IDisposable
    {
        private FaceRegistrationApi instance;

        public FaceRegistrationApiTests()
        {
            instance = new FaceRegistrationApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FaceRegistrationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' FaceRegistrationApi
            //Assert.IsType<FaceRegistrationApi>(instance);
        }

        /// <summary>
        /// Test FaceRegistrationRegisterPost
        /// </summary>
        [Fact]
        public void FaceRegistrationRegisterPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Registration registration = null;
            //instance.FaceRegistrationRegisterPost(registration);
        }
    }
}
