/*
 * FaceRecognitionDotNet Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using FaceRecognitionDotNet.Client.Client;
using FaceRecognitionDotNet.Client.Api;
// uncomment below to import models
//using FaceRecognitionDotNet.Client.Model;

namespace FaceRecognitionDotNet.Client.Test.Api
{
    /// <summary>
    ///  Class for testing FaceEncodingApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class FaceEncodingApiTests : IDisposable
    {
        private FaceEncodingApi instance;

        public FaceEncodingApiTests()
        {
            instance = new FaceEncodingApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FaceEncodingApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' FaceEncodingApi
            //Assert.IsType<FaceEncodingApi>(instance);
        }

        /// <summary>
        /// Test FaceEncodingEncodingPost
        /// </summary>
        [Fact]
        public void FaceEncodingEncodingPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Image image = null;
            //var response = instance.FaceEncodingEncodingPost(image);
            //Assert.IsType<Encdoing>(response);
        }
    }
}
