/*
 * FaceRecognitionDotNet Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FaceRecognitionDotNet.Client.Api;
using FaceRecognitionDotNet.Client.Model;
using FaceRecognitionDotNet.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FaceRecognitionDotNet.Client.Test.Model
{
    /// <summary>
    ///  Class for testing FaceArea
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FaceAreaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FaceArea
        //private FaceArea instance;

        public FaceAreaTests()
        {
            // TODO uncomment below to create an instance of FaceArea
            //instance = new FaceArea();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FaceArea
        /// </summary>
        [Fact]
        public void FaceAreaInstanceTest()
        {
            // TODO uncomment below to test "IsType" FaceArea
            //Assert.IsType<FaceArea>(instance);
        }


        /// <summary>
        /// Test the property 'Bottom'
        /// </summary>
        [Fact]
        public void BottomTest()
        {
            // TODO unit test for the property 'Bottom'
        }
        /// <summary>
        /// Test the property 'Left'
        /// </summary>
        [Fact]
        public void LeftTest()
        {
            // TODO unit test for the property 'Left'
        }
        /// <summary>
        /// Test the property 'Right'
        /// </summary>
        [Fact]
        public void RightTest()
        {
            // TODO unit test for the property 'Right'
        }
        /// <summary>
        /// Test the property 'Top'
        /// </summary>
        [Fact]
        public void TopTest()
        {
            // TODO unit test for the property 'Top'
        }

    }

}
