/*
 * FaceRecognitionDotNet Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FaceRecognitionDotNet.Client.Api;
using FaceRecognitionDotNet.Client.Model;
using FaceRecognitionDotNet.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FaceRecognitionDotNet.Client.Test.Model
{
    /// <summary>
    ///  Class for testing Image
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ImageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Image
        //private Image instance;

        public ImageTests()
        {
            // TODO uncomment below to create an instance of Image
            //instance = new Image();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Image
        /// </summary>
        [Fact]
        public void ImageInstanceTest()
        {
            // TODO uncomment below to test "IsType" Image
            //Assert.IsType<Image>(instance);
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
