/*
 * FaceRecognitionDotNet Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FaceRecognitionDotNet.Client.Api;
using FaceRecognitionDotNet.Client.Model;
using FaceRecognitionDotNet.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace FaceRecognitionDotNet.Client.Test.Model
{
    /// <summary>
    ///  Class for testing Registration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RegistrationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Registration
        //private Registration instance;

        public RegistrationTests()
        {
            // TODO uncomment below to create an instance of Registration
            //instance = new Registration();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Registration
        /// </summary>
        [Fact]
        public void RegistrationInstanceTest()
        {
            // TODO uncomment below to test "IsType" Registration
            //Assert.IsType<Registration>(instance);
        }


        /// <summary>
        /// Test the property 'Demographics'
        /// </summary>
        [Fact]
        public void DemographicsTest()
        {
            // TODO unit test for the property 'Demographics'
        }
        /// <summary>
        /// Test the property 'Encoding'
        /// </summary>
        [Fact]
        public void EncodingTest()
        {
            // TODO unit test for the property 'Encoding'
        }
        /// <summary>
        /// Test the property 'Photo'
        /// </summary>
        [Fact]
        public void PhotoTest()
        {
            // TODO unit test for the property 'Photo'
        }

    }

}
